version: 2
jobs:
  build_and_test:
    working_directory: ~/sdk
    docker:
      - image: circleci/android:api-30
    steps:
      - checkout
      - run:
          name: Accept licenses
          command: yes | sdkmanager --licenses || true
      - run:
          name: Build
          command: ./gradlew check
      - store_test_results:
          path: build/test-results/testDebugUnitTest/TEST-io.radar.sdk.RadarTest.xml
      - store_artifacts:
          path: build/reports/jacoco/jacocoTestReport/html
          destination: test-coverage
      - store_artifacts:
          path: build/reports/detekt/debug.html
          destination: static-analysis
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
