version: 2.1
orbs:
  android: circleci/android@1.0.3
jobs:
  build_and_test:
    docker:
      - image: circleci/android:api-30
    steps:
      - checkout
      - run:
          name: Accept licenses
          command: yes | sdkmanager --licenses || true
      - android/create-avd:
          avd-name: radar_avd
          system-image: system-images;android-30;default;x86
          install: true
      - android/start-emulator:
          avd-name: radar_avd
          no-window: true
      - run:
          name: Build
          command: ./gradlew check
      # JUnit Test Results
      - store_test_results:
          path: sdk/build/test-results/testDebugUnitTest/TEST-io.radar.sdk.RadarTest.xml
      # Jacoco Coverage Report
      - store_artifacts:
          path: sdk/build/reports/jacoco/jacocoTestReport/html
          destination: jacoco
      # Lint Static Analysis Report
      - store_artifacts:
          path: sdk/build/reports/lint-results.html
      # Detekt Static Analysis Report
      - store_artifacts:
          path: sdk/build/reports/detekt/debug.html
          destination: detekt-results.html
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
